/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 public/AirwaySegment.glb -t 
*/

import * as THREE from "three";
import React from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    GEN0: THREE.Mesh;
    GEN1: THREE.Mesh;
    GEN2: THREE.Mesh;
    GEN3: THREE.Mesh;
    GEN4: THREE.Mesh;
    GEN5: THREE.Mesh;
    GEN6: THREE.Mesh;
  };
  materials: {
    Material: THREE.MeshStandardMaterial;
    ["Material.001"]: THREE.MeshStandardMaterial;
    ["Material.020"]: THREE.MeshStandardMaterial;
    ["Material.021"]: THREE.MeshStandardMaterial;
    ["Material.022"]: THREE.MeshStandardMaterial;
    ["Material.023"]: THREE.MeshStandardMaterial;
    ["Material.024"]: THREE.MeshStandardMaterial;
  };
};

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("./AirwaySegment.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.GEN0.geometry}
        material={materials.Material}
        position={[-266.007, 526.231, 49.153]}
        rotation={[-2.083, 0, 0]}
      />
      <mesh
        geometry={nodes.GEN1.geometry}
        material={materials["Material.001"]}
        position={[-266.007, 526.231, 49.153]}
        rotation={[-2.083, 0, 0]}
      />
      <mesh
        geometry={nodes.GEN2.geometry}
        material={materials["Material.020"]}
        position={[-266.007, 526.231, 49.153]}
        rotation={[-2.083, 0, 0]}
      />
      <mesh
        geometry={nodes.GEN3.geometry}
        material={materials["Material.021"]}
        position={[-266.007, 526.231, 49.153]}
        rotation={[-2.083, 0, 0]}
      />
      <mesh
        geometry={nodes.GEN4.geometry}
        material={materials["Material.022"]}
        position={[-266.007, 526.231, 49.153]}
        rotation={[-2.083, 0, 0]}
      />
      <mesh
        geometry={nodes.GEN5.geometry}
        material={materials["Material.023"]}
        position={[-266.007, 526.231, 49.153]}
        rotation={[-2.083, 0, 0]}
      />
      <mesh
        geometry={nodes.GEN6.geometry}
        material={materials["Material.024"]}
        position={[-266.007, 526.231, 49.153]}
        rotation={[-2.083, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/AirwaySegment.glb");
