/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 public/MouseAirWaysImage.glb -t 
*/

import * as THREE from "three";
import React from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    MouseAirwayCast: THREE.Mesh;
  };
  materials: {
    ["Material.001"]: THREE.MeshStandardMaterial;
  };
};

export default function Model2(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/MouseAirWaysImage.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.MouseAirwayCast.geometry}
        material={materials["Material.001"]}
      />
    </group>
  );
}

useGLTF.preload("/MouseAirWaysImage.glb");
